// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFIUp66Yu_M4wOXomdktYFITjCY1rEFw',
    appId: '1:987088242836:web:aa97191168c3fa8c5c8c81',
    messagingSenderId: '987088242836',
    projectId: 'flora-app-ded12',
    authDomain: 'flora-app-ded12.firebaseapp.com',
    storageBucket: 'flora-app-ded12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARCLfIjBq_NW_Jucoyi-G0jAtMiCOJtNo',
    appId: '1:987088242836:android:bd2b297eacc3a7cd5c8c81',
    messagingSenderId: '987088242836',
    projectId: 'flora-app-ded12',
    storageBucket: 'flora-app-ded12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXydLb9LFaAU2TFz4Tc_SZ3xXEvFb4Lt8',
    appId: '1:987088242836:ios:30f2c67bc687264f5c8c81',
    messagingSenderId: '987088242836',
    projectId: 'flora-app-ded12',
    storageBucket: 'flora-app-ded12.firebasestorage.app',
    iosBundleId: 'com.example.floraMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXydLb9LFaAU2TFz4Tc_SZ3xXEvFb4Lt8',
    appId: '1:987088242836:ios:30f2c67bc687264f5c8c81',
    messagingSenderId: '987088242836',
    projectId: 'flora-app-ded12',
    storageBucket: 'flora-app-ded12.firebasestorage.app',
    iosBundleId: 'com.example.floraMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPFIUp66Yu_M4wOXomdktYFITjCY1rEFw',
    appId: '1:987088242836:web:ba2cf6beffce92635c8c81',
    messagingSenderId: '987088242836',
    projectId: 'flora-app-ded12',
    authDomain: 'flora-app-ded12.firebaseapp.com',
    storageBucket: 'flora-app-ded12.firebasestorage.app',
  );
}
