name: Distribute App via Firebase

on:
    pull_request:
        branches:
          - feature/FM-38-Firebase_App_Distribution
jobs:
  firebase_distribution:
    runs-on: ubuntu-latest  # Can be any supported runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload and Distribute App
        uses: mastersam07/firebase-app-distribution-action@v0.1
        with:
          serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          appId: ${{secrets.APP_ID}}
          file: build/app/outputs/flutter-apk/app-release.apk  # e.g., './build/app/outputs/flutter-apk/app-release.apk'
          groups: 'testers'  # Optional: distribution groups