name: Distribute App via Firebase

on:
  pull_request:
    branches:
      - feature/FM-38-Firebase_App_Distribution

jobs:
  firebase_distribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Verify APK exists
        run: |
          ls -lh build/app/outputs/flutter-apk/
          file build/app/outputs/flutter-apk/app-release.apk
          
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.APP_ID}}
            serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
            groups: testers
            file: build/app/outputs/flutter-apk/app-release.apk
