name: Flutter Linting

on:
  pull_request:
    branches:
      - new-development  # أو "develop" حسب الفرع الذي تريد حمايته

jobs:
  lint:
    name: Run Flutter Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
